### PR TITLE
Office dashboard

### PR DESCRIPTION
**Pull request by grenzbotin**
@eicca pls have a look

### CODE REVIEW

**Comment by eicca** [comment]
Could you please exclude ` .DS_Store ` files?

**Comment by eicca** [comment]
Same goes for `.idea`

**Comment by eicca** [comment]
Also, all `tmp` files

**Comment by grenzbotin** [comment]
Hopefully excluded all useless files

**Comment by eicca** [comment]
There are still a few .DS_Store files :)

**Comment by eicca** [comment]
Also, development.sqlite3 probably shouldn't be commited.

**Comment by eicca** [comment]
Looks good to me other than that. Squash and merge :)

**Pull request merged**
